spring:
  application:
    name: docker-spring-server
server:
  port: 8443
  ssl:
    enabled: true
    #key-store: file:G:/Docker Projects/docker-spring-server/spring-server.p12
    key-store: file:/app/spring-server.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: docker-spring-server

python:
  server:
    url: https://python-server:5000 
    
webclient:
  ssl:
    trust-all-certificates: false
