spring:
  application:
    name: docker-kafka-spring-server
  kafka:
    bootstrap-servers: kafka-spring-py:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: spring-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.kdg.spring_server.dto
        spring.json.value.default.type: com.kdg.spring_server.dto.GreetingResponse
        spring.deserializer.value.fallback.type: org.apache.kafka.common.serialization.ByteArrayDeserializer
server:
  port: 8443
  ssl:
    enabled: true  
    key-store: file:/app/spring-server.p12   
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: docker-spring-server
    
